AppBundle\Entity\Offer:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\OfferRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        price:
            type: decimal
            precision: '7'
            scale: '2'
        updatedAt:
            type: datetime
    manyToOne:
        merchant:
            targetEntity: AppBundle\Entity\Merchant
            joinColumn:
                name: merchant_id
                referencedColumnName: id
        product:
            targetEntity: AppBundle\Entity\Product
            joinColumn:
                name: product_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
